modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL"

[[mods]]
modId="all_things_tinkers"
version="1.0.0"
displayName="All-Things-Tinkers"
authors="momosensei"
description='''All-Things-Tinkers.'''

[[dependencies.all_things_tinkers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.all_things_tinkers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"